version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: dusk-demo-app
    container_name: dusk-demo-app
    privileged: true
    volumes:
      - .:/srv/app
    ports:
      - 8080:2015
    links:
      - redisdb:redisdb
      - mysql:mysql
    environment:
      CONTAINER_ROLE: app
      DB_DATABASE: dusk_demo
      DB_HOST: mysql
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redisdb

  queue:
    build: .
    image: dusk-demo-app
    container_name: dusk-demo-queue
    volumes:
      - .:/srv/app
    links:
      - redisdb:redisdb
      - mysql:mysql
    environment:
      CONTAINER_ROLE: queue
      DB_DATABASE: dusk_demo
      DB_HOST: mysql
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redisdb

  scheduler:
    container_name: dusk-demo-scheduler
    image: dusk-demo-scheduler
    build:
      context: .
      dockerfile: docker/scheduler/Dockerfile
    privileged: true
    volumes:
      - .:/srv/app
    links:
      - redisdb:redisdb
      - mysql:mysql
    environment:
      DB_DATABASE: dusk_demo
      DB_HOST: mysql
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redisdb

  redisdb:
    container_name: dusk-demo-redis
    image: redis:3.0.7-alpine
    ports:
      - 16379:6379

  mysql:
    container_name: dusk-demo-mysql
    image: mysql:5.7
    ports:
     - 13306:3306
    environment:
      MYSQL_DATABASE: dusk_demo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: password
